### PR TITLE
Some fixes for newer versions of Node (v0.10 or higher)

### PR DESCRIPTION
**Pull request by pj-gomez**
Hello and thank you for your work.
I just wanted to contribute fixing some deprecated calls I found while testing it, should work with node v0.10 or higher. Tested on verions 5.2.0 for Linux and 5.1.0 for Windows (both server and client).

Best,
PJ.

### CODE REVIEW

**Comment by enobufs** [comment]
@pj-gomez Thanks so much for your PR. After 4 years of silence on the repo, I decided to update it to be a npm module. During the work, I also noticed that some of the code were not working due to the changes in nodejs and fixed them.

I created a branch called 'legacy' which has the old code (before I touched) for historical purpose. So, if you could create another PR on the 'legacy' branch, I would happy to accept the change.

**Comment by pj-gomez** [comment]
No problem @enobufs, I will move it to the legacy branch. It's good to know that you are working in the project again.

**Comment by enobufs** [comment]
Thanks!
>  It's good to know that you are working in the project again.

I will spare time maintaining this repo from now on. If you could take a look at the main branch, that would be awesome. I will be finalizing API soon.

I debating myself whether to stay with 'classic' stun protocol (RFC 3489), or to try implementing RFC 5389...

**Comment by pj-gomez** [comment]
Of course, I am having a look at the main branch and it looks great. 

I'm a bit rusty and quite busy, but I am willing to help as I can. STUN is going to be a key piece of infrastructure when WebRTC finally takes off and we need open, solid, modern implementations.

I am still beginning with RFC 5389, it's quite complex, but in the end I guess it's the way to go...

**Pull request closed without merging**
